### ISSUE TITLE
This test application does not work

### ISSUE THREAD

**Issue by XRayAdamo** [WindowsNotifications/NotificationListenerActionCenterApp#1]
This test application does not work ion my PC.
I actually created my own application, but since it does not work I decided to find another example. Your example give me the same error.

This exception is from my application.
_________
Error System.ArgumentOutOfRangeException: No mapping for the Unicode character exists in the target multi-byte code page. (Exception from HRESULT: 0x80070459)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Notification_Archive.Classes.AppSettings.<GatherNotifications>d__15.MoveNext()
_________________
and the error occurred here
IReadOnlyList<UserNotification> userNotifications = await listener.GetNotificationsAsync(NotificationKinds.Toast);

I reinstalled my Windows just week ago.

Do you have any ideas what could be wrong?

Thank you

**Comment by andrewleader** [comment]
Hey XRay, thanks for opening this issue!

Can you please share your notification database with us, so that we can inspect which notification is possibly causing this exception?

The issue seems to be caused by a specific notification, but we haven't been able to determine which notification is causing it.

**Here's how to get your notification database**
1. Open File Explorer
2. Enter the following path: _%LOCALAPPDATA%\Microsoft\Windows\Notifications_
3. Copy the _wpndatabase.db_ file
4. Attach that here, or if you're concerned about the contents of your notifications (this database includes your tile notifications), attach that in an email to WindowsNotifications@microsoft.com

Please make sure that the issue is still repro'ing before you grab a copy of the database, and then send it over!!

Thank you!
Andrew

**Comment by XRayAdamo** [comment]
Hi

I am really sorry for false alarm. Right after updates (applied yesterday after I posted this issue), everything started to work again. So I assume that the fix was published by Microsoft already. I just needed latest patches to be applied.

So my application is almost ready !
Thank you.

**Comment by XRayAdamo** [comment]
We can close this

**Comment by andrewleader** [comment]
Sorry to break the bad news, but it's an ongoing issue. What likely happened was the notification that was causing this went away. Until we are able to debug and find the root cause, this issue will intermittently happen.

So if you see it again, grab a copy of your notification database and send it to us!

**Comment by XRayAdamo** [comment]
Sure. If this happens again, I will let you know.
